import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import NextLink from "next/link";
import Footer from "../components/Footer";
import Navbar from "../components/Navbar";

const Home: NextPage = () => {
  return (
    <div className="app flex flex-col w-full min-h-screen">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />

      <main className="flex flex-col grow justify-center items-center">
        <NextLink href="/play" passHref>
          <button>play</button>
        </NextLink>
        <NextLink href="/learn" passHref>
          <button>learn</button>
        </NextLink>
        <NextLink href="/path-finding" passHref>
          <button>path finding</button>
        </NextLink>

        <NextLink href="/login" passHref>
          <button>login</button>
        </NextLink>

        <NextLink href="/register" passHref>
          <button>register</button>
        </NextLink>
      </main>

      <Footer />
    </div>
  );
};

export default Home;
